# Generated by Django 3.1.7 on 2021-04-04 10:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210316_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subcats', to='app.category', verbose_name='Название категории статей'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата обновлнения'),
        ),
    ]
